<?php

include('header.php');

?>

<div class="header-bread columns small-12">
	<div class="row">
		<?php

		Login();
		Register();

		?>
		<div class="header-crump column small-12">
			<ul class="breadcrumbs">
			    <li><a href="../index.php">Home</a></li>
			    <li><a href="terms.php">Policies</a></li>
			    <li><a href="privacy.php" class="current-nav">Privacy Policy</a></li>
			</ul>
		</div>
	</div>
</div>

<div class="row">
	<div class="content columns small-12 medium-12">
		<div class="row">
			<div class="content-box column small-12 medium-12">
				<div class="box-header">
					Privacy Policy
				</div>

				<div class="box-content">
					<div class="policy-box grey">
						<span class="bold">PRIVACY POLICY</span>
						<br>
						THIS PRIVACY POLICY HAS BEEN COMPILED TO BETTER SERVE THOSE WHO ARE CONCERNED WITH HOW THEIR 'PERSONALLY IDENTIFIABLE INFORMATION' (PII) IS BEING USED ONLINE. PII, AS USED IN US PRIVACY LAW AND INFORMATION SECURITY, IS INFORMATION THAT CAN BE USED ON ITS OWN OR WITH OTHER INFORMATION TO IDENTIFY, CONTACT, OR LOCATE A SINGLE PERSON, OR TO IDENTIFY AN INDIVIDUAL IN CONTEXT. PLEASE READ OUR PRIVACY POLICY CAREFULLY TO GET A CLEAR UNDERSTANDING OF HOW WE COLLECT, USE, PROTECT OR OTHERWISE HANDLE YOUR PERSONALLY IDENTIFIABLE INFORMATION IN ACCORDANCE WITH OUR WEBSITE.
						<br>
						<br>
						<span class="bold">WHAT PERSONAL INFORMATION DO WE COLLECT FROM THE PEOPLE THAT VISIT WEBSITE?</span>
						<br>
						WHEN REGISTERING ON OUR SITE, AS APPROPRIATE, YOU WILL BE ASKED TO ENTER YOUR EMAIL ADDRESS OR OTHER DETAILS TO AID IN IDENTIFYING YOUR ACCOUNT.
						<br>
						<br>
						<span class="bold">WHEN DO WE COLLECT INFORMATION?</span>
						<br>
						WE COLLECT INFORMATION FROM YOU WHEN YOU REGISTER ON OUR SITEOR ENTER INFORMATION ON OUR SITE.
						<br>
						<br>
						<span class="bold">HOW DO WE USE YOUR INFORMATION?</span>
						<br>
						<br>
						<span class="bold">WE MAY USE THE INFORMATION WE COLLECT FROM YOU WHEN YOU REGISTER, SURF THE WEBSITE, OR USE CERTAIN OTHER SITE FEATURES IN THE FOLLOWING WAYS:</span>
						<br>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- TO ALLOW US TO BETTER SERVICE YOU REGARDING FEATURES OR IN RESPONDING TO YOUR SUPPORT REQUESTS.
						<br>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- TO SEND PERIODIC EMAILS REGARDING YOUR ACCOUNT OR OTHER SERVICES.
						<br>
						<br>
						<span class="bold">HOW DO WE PROTECT VISITOR INFORMATION?</span>
						<br>
						OUR WEBSITE IS SCANNED ON A REGULAR BASIS FOR SECURITY HOLES AND KNOWN VULNERABILITIES IN ORDER TO MAKE YOUR VISIT TO OUR SITE AS SAFE AS POSSIBLE. INFORMATION STORED ON THE WEBSITE IS ENCRYPTED USING VARIOUS ALGORITHMS.
						<br>
						YOUR PERSONAL INFORMATION IS CONTAINED BEHIND SECURED NETWORKS AND IS ONLY ACCESSIBLE BY A LIMITED NUMBER OF PERSONS WHO HAVE SPECIAL ACCESS RIGHTS TO SUCH SYSTEMS, AND ARE REQUIRED TO KEEP THE INFORMATION CONFIDENTIAL. IN ADDITION, ALL SENSITIVE INFORMATION YOU SUPPLY IS ENCRYPTED VIA SECURE SOCKET LAYER (SSL) TECHNOLOGY.
						<br>
						WE IMPLEMENT A VARIETY OF SECURITY MEASURES WHEN A USER REGISTERS AN ACCOUNT, SUBMITS, OR ACCESSES THEIR INFORMATION, USES FEATURES TO MAINTAIN THE SAFETY OF YOUR PERSONAL INFORMATION.
						<br>
						ALL TRANSACTIONS ARE PROCESSED THROUGH A GATEWAY PROVIDER AND ARE NOT STORED OR PROCESSED ON OUR SERVERS.
						<br>
						<br>
						<span class="bold">DO WE USE 'COOKIES'?</span>
						<br>
						YES. COOKIES ARE SMALL FILES THAT A SITE OR ITS SERVICE PROVIDER TRANSFERS TO YOUR COMPUTER'S HARD DRIVE THROUGH YOUR WEB BROWSER (IF YOU ALLOW) THAT ENABLES THE SITE'S OR SERVICE PROVIDER'S SYSTEMS TO RECOGNIZE YOUR BROWSER AND CAPTURE AND REMEMBER CERTAIN INFORMATION. FOR INSTANCE, WE USE COOKIES TO HELP US AUTOMATICALLY REMEMBER YOU FOR YOUR NEXT VISIT. THEY ARE ALSO USED TO HELP US UNDERSTAND YOUR PREFERENCES BASED ON PREVIOUS OR CURRENT SITE ACTIVITY, WHICH ENABLES US TO PROVIDE YOU WITH IMPROVED SERVICES. WE ALSO USE COOKIES TO HELP US COMPILE AGGREGATE DATA ABOUT SITE TRAFFIC AND SITE INTERACTION SO THAT WE CAN OFFER BETTER SITE EXPERIENCES AND TOOLS IN THE FUTURE.
						<br>
						<br>
						<span class="bold">WE USE COOKIES TO:</span>
						<br>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- UNDERSTAND AND SAVE USER'S PREFERENCES FOR FUTURE VISITS.
						<br>
						YOU CAN CHOOSE TO HAVE YOUR COMPUTER WARN YOU EACH TIME A COOKIE IS BEING SENT, OR YOU CAN CHOOSE TO TURN OFF ALL COOKIES. YOU DO THIS THROUGH YOUR BROWSER (LIKE INTERNET EXPLORER) SETTINGS. EACH BROWSER IS A LITTLE DIFFERENT, SO LOOK AT YOUR BROWSER'S HELP MENU TO LEARN THE CORRECT WAY TO MODIFY YOUR COOKIES.
						<br>
						<br>
						<span class="bold">IF USERS DISABLE COOKIES IN THEIR BROWSER:</span>
						<br>
						IF YOU DISABLE COOKIES, SOME FEATURES WILL BE DISABLED. IT WILL TURN OFF SOME OF THE FEATURES THAT MAKE YOUR SITE EXPERIENCE MORE EFFICIENT AND SOME OF OUR SERVICES WILL NOT FUNCTION PROPERLY.
						<br>
						FEATURES THAT WILL BE DISABLED
						<br>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- REMEMBER ME FEATURE
						<br>
						<br>
						<span class="bold">THIRD PARTY DISCLOSURE</span>
						<br>
						WE DO NOT SELL, TRADE, OR OTHERWISE TRANSFER TO OUTSIDE PARTIES YOUR PERSONALLY IDENTIFIABLE INFORMATION.
						<br>
						<br>
						<span class="bold">THIRD PARTY LINKS</span>
						<br>
						WE DO NOT INCLUDE OR OFFER THIRD PARTY PRODUCTS OR SERVICES ON OUR WEBSITE.
						<br>
						<br>
						<span class="bold">ACCORDING TO CALOPPA WE AGREE TO THE FOLLOWING:</span>
						<br>
						USERS CAN VISIT OUR SITE ANONYMOUSLY
						<br>
						ONCE THIS PRIVACY POLICY IS CREATED, WE WILL ADD A LINK TO IT ON OUR HOME PAGE, OR AS A MINIMUM ON THE FIRST SIGNIFICANT PAGE AFTER ENTERING OUR WEBSITE.
						<br>
						OUR PRIVACY POLICY LINK INCLUDES THE WORD 'PRIVACY', AND CAN BE EASILY BE FOUND ON THE PAGE SPECIFIED ABOVE.
						<br>
						<br>
						<span class="bold">USERS WILL BE NOTIFIED OF ANY PRIVACY POLICY CHANGES:</span>
						<br>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- ON OUR PRIVACY POLICY PAGE
						<br>
						<br>
						<span class="bold">USERS ARE ABLE TO CHANGE THEIR PERSONAL INFORMATION:</span>
						<br>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- BY LOGGING IN TO THEIR ACCOUNT
						<br>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- BY SENDING US A SUPPORT TICKET
						<br>
						<br>
						<span class="bold">HOW DOES OUR SITE HANDLE DO NOT TRACK SIGNALS?</span>
						<br>
						WE HONOR DO NOT TRACK SIGNALS AND DO NOT TRACK, PLANT COOKIES, OR USE ADVERTISING WHEN A DO NOT TRACK (DNT) BROWSER MECHANISM IS IN PLACE. DOES OUR SITE ALLOW THIRD PARTY BEHAVIORAL TRACKING?
						<br>
						WE DO NOT ALLOW THIRD PARTY BEHAVIORAL TRACKING
						<br>
						<br>
						<span class="bold">CONTACTING US</span>
						<br>
						IF THERE ARE ANY QUESTIONS REGARDING THIS PRIVACY POLICY YOU MAY CONTACT US USING THE INFORMATION BELOW.
						<br>
						<a href="http://worldofnorthcraft.com/forums/">www.worldofnorthcraft.com</a>
						<br>
						<a href="mailto:support@worldofnorthcraft.com">support@worldofnorthcraft.com</a>
					</div>
				</div>	
			</div>
		</div>
	</div>
</div>

<?php

include('footer.php');

?>