<?php

include('header.php');

?>

<div class="header-bread columns small-12">
	<div class="row">
		<?php

		Login();
		Register();

		?>
		<div class="header-crump column small-12">
			<ul class="breadcrumbs">
			    <li><a href="../index.php">Home</a></li>
			    <li><a href="terms.php">Policies</a></li>
			    <li><a href="refund.php" class="current-nav">Refund Policy</a></li>
			</ul>
		</div>
	</div>
</div>

<div class="row">
	<div class="content columns small-12 medium-12">
		<div class="row">
			<div class="content-box column small-12 medium-12">
				<div class="box-header">
					Refund Policy
				</div>

				<div class="box-content">
					<div class="policy-box grey">
						<span class="bold">IN THIS AGREEMENT THE FOLLOWING TERMS WILL HAVE THE FOLLOWING MEANINGS</span>
						<br>
						<br>
						"ACCOUNT" MEANS COLLECTIVELY THE PERSONAL INFORMATION AND CRIDENTIALS USED BY USERS TO ACCESS COINS, VIRTUAL ITEMS AND / OR ANY COMMUNICATIONS SYSTEMS ON THIS WEBSITE;
						<br>
						<br>
						"LICENCE" MEANS THE TERMS AND CONDITIONS GOVERNING YOUR USE OF COINS, VIRTUAL ITEMS OR SERVICES PURCHASED FROM THIS WEBSITE;
						<br>
						<br>
						"VIRTUAL ITEMS" MEANS, IN-GAME VIRTUAL ITEMS THAT PREMIUM MANAGEMENT L.P. DELIVERS THROUGH USE OF THE WEBSITE STORE IN EXCHANGE OF COINS;
						<br>
						<br>
						"UNUSED VIRTUAL ITEM" MEANS A VIRTUAL ITEM PURCHASED FROM A DESIGNATED VIRTUAL SHOP THAT IS KEPT INSIDE OF IN-GAME MAILBOX AND NEVER WITHDRAWN OUT OF IT.
						<br>
						<br>
						"COIN" MEANS VIRTUAL COINS THAT PREMIUM MANAGEMENT L.P. MAKES AVAILABLE FOR PURCHASE BY USERS SUBJECT TO THE TERMS OF THE APPROPRIATE LICENSE. ALL OBTAINED COINS ARE VALID FOR 30 CALENDAR DAYS;
						<br>
						<br>
						"SERVICE" MEANS COLLECTIVELY ANY ONLINE FACILITIES, TOOLS, SERVICES OR INFORMATION THAT PREMIUM MANAGEMENT L.P. MAKES AVAILABLE THROUGH THE WEBSITE EITHER NOW OR IN THE FUTURE;
						<br>
						<br>
						"PAYMENT INFORMATION" MEANS ANY DETAILS REQUIRED FOR THE PURCHASE OF COINS FROM THIS WEBSITE. THIS INCLUDES, BUT IS NOT LIMITED TO, NAMES, ADDRESSES, CREDIT / DEBIT CARD NUMBERS, BANK ACCOUNT NUMBERS AND SORT CODES;
						<br>
						<br>
						"PURCHASE INFORMATION" MEANS COLLECTIVELY ANY ORDERS, INVOICES, CONFIRMATION EMAILS, RECEIPTS OR SIMILAR THAT MAY BE IN HARD COPY OR ELECTRONIC FORM;
						<br>
						<br>
						"SYSTEM" MEANS ANY ONLINE COMMUNICATIONS INFRASTRUCTURE THAT PREMIUM MANAGEMENT L.P. MAKES AVAILABLE THROUGH THE WEBSITE EITHER NOW OR IN THE FUTURE. THIS INCLUDES, BUT IS NOT LIMITED TO, WEB-BASED EMAIL, MESSAGE BOARDS, LIVE CHAT FACILITIES AND EMAIL LINKS;
						<br>
						<br>
						"USER" / "USERS" MEANS ANY THIRD PARTY THAT ACCESSES THE WEBSITE AND IS NOT EMPLOYED BY PREMIUM MANAGEMENT L.P. AND ACTING IN THE COURSE OF THEIR EMPLOYMENT;
						<br>
						<br>
						"WEBSITE" MEANS THE WEBSITE THAT YOU ARE CURRENTLY USING WWW.WARMANE.COM AND ANY SUB-DOMAINS OF THIS SITE (E.G. SUBDOMAIN FORUM.MOLTEN-WOW.COM) UNLESS EXPRESSLY EXCLUDED BY THEIR OWN TERMS AND CONDITIONS.
						<br>
						<br>
						PREMIUM MANAGEMENT L.P. AIMS TO ALWAYS PROVIDE HIGH QUALITY VIRTUAL ITEMS (OBTAINED IN EXCHANGE FOR COINS) THAT IS FAULT FREE. FAULTS INCLUDE AND ARE NOT LIMITED TO DATA CORRUPTION.
						<br>
						<br>
						THIS REFUND POLICY COVERS ONLY FAULTS THAT IMPAIR THE USE OF THE COINS.
						<br>
						<br>
						THIS REFUND POLICY DOES NOT COVER USE DIFFICULTIES ARISING OUT OF ISSUES SUCH AS FILE INCOMPATIBILITY OR MINOR MISTAKES IN VIRTUAL ITEMS ITSELF SUCH AS SPELLING ERRORS OR GRAPHICAL FAULTS THAT DO NOT RESULT FROM DATA CORRUPTION.
						<br>
						<br>
						COINS CANNOT BE EXCHANGED BACK INTO A CURRENCY. PURCHASES OF COINS SETS ARE NOT REFUNDABLE.
						<br>
						<br>
						IF A PURCHASED SET OF COINS IS NOT EXCHANGED INTO THE VIRTUAL ITEMS DURING 30 CALENDAR DAYS IT THEN IS NO LONGER VALID AND CANNOT BE A SUBJECT OF REFUND. REFUND REQUESTS OF COINS PURCHASES WITHIN 30 CALENDAR DAYS ARE AT THE EXCLUSIVE DISCRETION OF PREMIUM MANAGEMENT L.P. MANAGEMENT. IF A VIRTUAL ITEM WAS GIVEN TO A USER ON TERMS OF BONUS, GIFT OR PROMOTION THEN IT CANNOT BE A SUBJECT OF REFUND INTO COINS.
						<br>
						<br>
						IF A VIRTUAL ITEM CONTAINS FAULTS ON RECEIVING, YOU SHOULD INFORM PREMIUM MANAGEMENT L.P. IMMEDIATELY AND MUST INFORM US WITHIN 24 HOURS OF RECEIVING IN ORDER TO RECEIVE COINS BACK EQUAL TO THE PURCHASE PRICE OF THE RELEVANT VIRTUAL ITEM. ANY NOTIFICATION RECEIVED OUTSIDE OF THIS TIME PERIOD IS AT THE EXCLUSIVE DISCRETION OF PREMIUM MANAGEMENT L.P. MANAGEMENT.
						<br>
						<br>
						ACCIDENTAL PURCHASES OF COINS OCCURRED AS A RESULT OF TECHNICAL FAULT IN THE PAYMENT SYSTEM YOU PAID THROUGH MUST BE DISPUTED WITH THE RESPECTIVE PAYMENT PROCESSOR. PREMIUM MANAGEMENT L.P. IS NOT RESPONSIBLE FOR ANY TECHNICAL FAULTS ARISING AT PAYMENT PROCESSORS. PREMIUM MANAGEMENT L.P. IS NOT IN CHARGE OF HANDLING CREDIT/DEBIT AND BANK TRANSACTIONS UNDERTAKEN TO PURCHASE COINS.
						<br>
						<br>
						WHERE ANY REFUND IS ISSUED UNDER ANY CIRCUMSTANCES, PREMIUM MANAGEMENT L.P. RESERVES THE RIGHT TO SUSPEND OR TERMINATE THE RESPECTIVE ACCOUNT WITH THE WEBSITE.
						<br>
						<br>
						<span class="bold">FOR ALL ENQUIRIES ABOUT THE STATUS OF YOUR ORDERS, PLEASE CONTACT US:</span>
						<br>
						<br>
						<a href="mailto:support@worldofnorthcraft.com">support@worldofnorthcraft.com</a>
					</div>
				</div>	
			</div>
		</div>
	</div>
</div>

<?php

include('footer.php');

?>